const STORAGE='muskelcoach-v1';
const defaultState={tab:'home',setup:false,days:3,level:'Einsteiger',duration:35,equipment:{chair:true,table:true,rower:true},completed:[],currentDay:0,ratings:{},currentExercise:0};
let state=load();
function load(){try{return {...defaultState,...JSON.parse(localStorage.getItem(STORAGE)||'{}')}}catch{return {...defaultState}}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state))}
const GIF_BASE='gifs/';
const exerciseGifs={
 pushup:'0662-I4hDWkc.gif',
 squat:'1685-QChZi3x.gif',
 pike:'0662-I4hDWkc.gif',
 split:'v8-reverse-lunge.gif',
 plank:'0664-KhHJ338.gif',
 rower:'1323-SJqRxOt.gif',
 tableRow:'v8-ytw-raises.gif',
 superman:'0609-bLyQokI.gif',
 reverseAngel:'0609-bLyQokI.gif',
 hollow:'0001-2gPfomN.gif',
 chairDip:'v8-diamond-pushups.gif',
 lunge:'2368-9E25EOx.gif',
 declinePush:'v8-close-pushups.gif',
 glute:'3561-GibBPPg.gif',
 sidePlank:'0664-KhHJ338.gif'
};
const plans={
  A:{name:'Push & Beine',focus:'Brust • Schulter • Beine',ex:['pushup','squat','pike','split','plank']},
  B:{name:'Rücken & Core',focus:'Rücken • hintere Schulter • Bauch',ex:['rower','tableRow','superman','reverseAngel','hollow']},
  C:{name:'Ganzkörper Kraft',focus:'Beine • Brust • Core',ex:['chairDip','lunge','declinePush','glute','sidePlank']}
};
const exercises={
 pushup:{n:'Liegestütz',m:'Brust, Trizeps',s:'3–4 Sätze × 6–15 Wdh.',tip:'Körper bleibt gerade, Brust kontrolliert Richtung Boden. 1–2 Wiederholungen im Tank lassen.',how:'Hände etwas breiter als schulterbreit aufsetzen. Bauch und Gesäß anspannen. Den Körper als feste Linie absenken, bis die Brust kurz über dem Boden ist, anschließend gleichmäßig hochdrücken.',errors:'Hohlkreuz, hochgezogene Schultern und weit nach außen gestellte Ellbogen vermeiden.',breath:'Beim Absenken einatmen, beim Hochdrücken ausatmen.',easy:'Knie-Liegestütze oder Hände erhöht an einer Wand.',hard:'Langsames Absenken, Pause unten oder Archer Push-ups.'},
 squat:{n:'Kniebeuge',m:'Beine, Gesäß',s:'4 Sätze × 8–20 Wdh.',tip:'Knie folgen den Fußspitzen, Rücken stabil, langsam absenken.',how:'Füße etwa schulterbreit stellen, Fußspitzen leicht nach außen. Hüfte nach hinten und unten führen, dabei den Oberkörper stabil halten. Über den ganzen Fuß wieder aufrichten.',errors:'Knie nicht nach innen fallen lassen und die Fersen nicht vom Boden lösen.',breath:'Beim Absenken einatmen, beim Aufstehen ausatmen.',easy:'Nur so tief gehen, wie die Haltung sauber bleibt.',hard:'Langsame Wiederholungen, Pause unten oder einbeinige Varianten vorbereiten.'},
 pike:{n:'Pike Push-up',m:'Schulter',s:'3 Sätze × 6–12 Wdh.',tip:'Hüfte hoch, Kopf Richtung Boden, kontrollierte Wiederholungen.',how:'Aus dem Liegestütz die Hüfte hochschieben, sodass der Körper ein umgedrehtes V bildet. Ellbogen beugen und den Kopf kontrolliert zwischen den Händen Richtung Boden führen. Danach kräftig hochdrücken.',errors:'Hüfte nicht absinken lassen und den Kopf nicht vor den Händen absetzen.',breath:'Beim Absenken einatmen, beim Hochdrücken ausatmen.',easy:'Hände erhöht auf einer stabilen Fläche oder kleinere Bewegungsamplitude.',hard:'Füße erhöht oder langsamere negative Phase.'},
 split:{n:'Reverse Lunge',m:'Beine, Gesäß',s:'3 Sätze × 6–12 je Seite',tip:'Großer Schritt nach hinten. Vorderes Knie stabil halten.',how:'Aufrecht stehen und mit einem Bein einen ausreichend großen Schritt nach hinten machen. Das hintere Knie Richtung Boden senken, während das vordere Bein stabil bleibt. Über die vordere Ferse zurückdrücken.',errors:'Zu kurzer Schritt, einknickendes Vorderknie und nach vorn fallender Oberkörper.',breath:'Beim Absenken einatmen, beim Hochdrücken ausatmen.',easy:'Kleinere Tiefe oder leicht an einer Wand abstützen.',hard:'Langsames Absenken, Pause unten oder zusätzliche Wiederholungen pro Seite.'},
 plank:{n:'Unterarmstütz',m:'Core',s:'3 Sätze × 25–60 Sek.',tip:'Rippen runter, Po leicht angespannt, nicht durchhängen.',how:'Unterarme parallel aufsetzen, Ellbogen unter den Schultern. Beine strecken und den Körper von Kopf bis Ferse in einer Linie halten. Bauch und Gesäß dauerhaft anspannen.',errors:'Durchhängende Hüfte, hochgestreckter Po und nach vorn geschobener Kopf.',breath:'Ruhig und gleichmäßig weiteratmen, nicht die Luft anhalten.',easy:'Knie am Boden absetzen.',hard:'Längere Haltezeit oder abwechselnd einen Fuß leicht anheben.'},
 rower:{n:'Rudergerät – Kraftzüge',m:'Rücken, Bizeps',s:'5 Sätze × 8–15 kräftige Züge',tip:'Hoher Widerstand, explosiv ziehen, langsam zurück. Kein Cardio-Tempo.',how:'Mit geradem Rücken starten, über die Beine Druck aufbauen und anschließend den Griff kraftvoll zum unteren Brustkorb ziehen. Die Rückbewegung langsam kontrollieren: Arme, Oberkörper, dann Beine.',errors:'Rundrücken, ausschließlich aus den Armen ziehen und hektisch zurückrollen.',breath:'Beim kräftigen Zug ausatmen, auf dem Rückweg einatmen.',easy:'Widerstand reduzieren und Bewegung technisch langsamer ausführen.',hard:'Widerstand erhöhen oder die Rückbewegung deutlich verlangsamen.'},
 tableRow:{n:'Y-T-W Raises in Bauchlage',m:'oberer Rücken, hintere Schulter',s:'3 Sätze × 6–12 Durchgänge',tip:'Arme in Y-, T- und W-Form anheben und Schulterblätter aktiv zusammenziehen.',how:'In Bauchlage Stirn knapp über dem Boden halten. Arme zuerst schräg nach vorn als Y, dann seitlich als T und anschließend mit gebeugten Ellbogen als W anheben. Jede Position kurz kontrolliert halten.',errors:'Schultern zu den Ohren ziehen, Schwung holen oder den Kopf stark überstrecken.',breath:'Beim Anheben ausatmen, beim Absenken einatmen.',easy:'Nur eine der drei Armpositionen ausführen.',hard:'Positionen länger halten oder sehr langsame Wiederholungen machen.'},
 superman:{n:'Superman Hold',m:'Rückenstrecker',s:'3 Sätze × 20–45 Sek.',tip:'Arme und Beine leicht anheben, Nacken neutral halten.',how:'In Bauchlage Arme nach vorn strecken. Arme, Brust und Beine nur so weit anheben, dass die Bewegung kontrolliert bleibt. Gesäß und Rückenstrecker anspannen.',errors:'Zu hoch ins Hohlkreuz ziehen, ruckartig anheben oder den Kopf überstrecken.',breath:'Ruhig und gleichmäßig atmen.',easy:'Nur Arme oder nur Beine anheben.',hard:'Länger halten oder kleine kontrollierte Impulse ausführen.'},
 reverseAngel:{n:'Reverse Snow Angels',m:'oberer Rücken',s:'3 Sätze × 8–15 Wdh.',tip:'Bauchlage, Arme langsam seitlich führen, Schulterblätter aktiv.',how:'In Bauchlage die Arme knapp über dem Boden halten. Von der Position neben den Hüften langsam in einem großen Bogen nach vorn führen und wieder zurück. Schulterblätter aktiv nach hinten unten ziehen.',errors:'Arme auf dem Boden schleifen lassen, Schwung nutzen oder Schultern hochziehen.',breath:'Beim Vorführen einatmen, beim Zurückführen ausatmen.',easy:'Kleinere Bewegungsamplitude.',hard:'Sehr langsam arbeiten oder an den Endpunkten kurz halten.'},
 hollow:{n:'Hollow Hold',m:'Bauch',s:'3 Sätze × 15–45 Sek.',tip:'Lendenwirbelsäule bleibt am Boden. Leichtere Variante mit angewinkelten Beinen.',how:'Auf den Rücken legen und den unteren Rücken fest in den Boden drücken. Schulterblätter und Beine leicht anheben. Arme je nach Schwierigkeit nach vorn oder über den Kopf strecken.',errors:'Unterer Rücken löst sich vom Boden, Beine werden zu tief gehalten oder die Luft wird angehalten.',breath:'Kurz und kontrolliert weiteratmen, Bauchspannung beibehalten.',easy:'Knie anwinkeln und Arme neben dem Körper halten.',hard:'Beine tiefer und Arme vollständig über den Kopf strecken.'},
 chairDip:{n:'Diamond Push-ups',m:'Trizeps, Brust',s:'3 Sätze × 6–12 Wdh.',tip:'Hände eng unter der Brust. Ellbogen nah am Körper führen.',how:'Hände unter der Brust so platzieren, dass Daumen und Zeigefinger annähernd eine Raute bilden. Körper gerade halten, Ellbogen eng führen und die Brust kontrolliert zu den Händen senken.',errors:'Ellbogen stark nach außen drehen, Hüfte durchhängen lassen oder Hände zu weit vorn platzieren.',breath:'Beim Absenken einatmen, beim Hochdrücken ausatmen.',easy:'Auf den Knien ausführen oder Hände etwas weiter auseinander setzen.',hard:'Langsam absenken oder unten kurz pausieren.'},
 lunge:{n:'Ausfallschritte',m:'Beine, Gesäß',s:'3 Sätze × 8–14 je Seite',tip:'Großer, stabiler Schritt. Oberkörper aufrecht, kontrollierte Bewegung.',how:'Aus dem aufrechten Stand einen großen Schritt nach vorn machen. Beide Knie beugen, bis das hintere Knie fast den Boden erreicht. Über die vordere Ferse zurück in den Stand drücken.',errors:'Zu schmal stehen, Vorderknie nach innen kippen lassen oder mit Schwung zurückspringen.',breath:'Beim Absenken einatmen, beim Hochdrücken ausatmen.',easy:'Weniger tief gehen oder abwechselnde Reverse Lunges nutzen.',hard:'Langsame Wiederholungen oder mehrere Wiederholungen auf einer Seite.'},
 declinePush:{n:'Enge Liegestütze',m:'Trizeps, Brust',s:'3 Sätze × 6–12 Wdh.',tip:'Hände schulterbreit oder enger. Körperspannung halten.',how:'Hände ungefähr schulterbreit oder etwas enger unter dem Oberkörper aufsetzen. Den ganzen Körper gespannt absenken und die Ellbogen nah am Rumpf führen. Anschließend gleichmäßig hochdrücken.',errors:'Ellbogen weit abspreizen, Schultern hochziehen oder die Hüfte absinken lassen.',breath:'Beim Absenken einatmen, beim Hochdrücken ausatmen.',easy:'Knie am Boden oder Hände an der Wand.',hard:'Hände enger setzen, langsam absenken oder unten pausieren.'},
 glute:{n:'Glute Bridge einbeinig',m:'Gesäß, Beinrückseite',s:'3 Sätze × 8–15 je Seite',tip:'Becken kontrolliert heben, oben kurz anspannen.',how:'Auf den Rücken legen, ein Bein aufstellen und das andere anheben. Über die Ferse des Standbeins das Becken anheben, bis Schulter, Hüfte und Knie eine Linie bilden. Oben Gesäß fest anspannen.',errors:'Aus dem Rücken statt aus dem Gesäß drücken, Becken verdrehen oder zu weit überstrecken.',breath:'Beim Anheben ausatmen, beim Absenken einatmen.',easy:'Beidbeinige Glute Bridge.',hard:'Oben länger halten oder Wiederholungen langsamer ausführen.'},
 sidePlank:{n:'Seitstütz',m:'seitlicher Core',s:'3 Sätze × 20–45 Sek. je Seite',tip:'Körper bildet eine Linie, Hüfte bleibt oben.',how:'Seitlich auf einen Unterarm stützen, Ellbogen unter der Schulter. Beine strecken und die Hüfte anheben, bis der Körper eine gerade Linie bildet. Die obere Schulter bleibt nach hinten geöffnet.',errors:'Hüfte absinken lassen, Schulter zum Ohr ziehen oder den Oberkörper nach vorn drehen.',breath:'Ruhig und gleichmäßig weiteratmen.',easy:'Unteres Knie am Boden absetzen.',hard:'Oberes Bein anheben oder kleine kontrollierte Hüftbewegungen ergänzen.'}
};
function todaysKeys(){return ['A','B','C','A','B'].slice(0,state.days)}
function currentPlan(){return todaysKeys()[state.currentDay%todaysKeys().length]}
function doneThisWeek(){const week=weekId();return state.completed.filter(x=>x.week===week).length}
function weekId(){const d=new Date();let onejan=new Date(d.getFullYear(),0,1);return `${d.getFullYear()}-${Math.ceil((((d-onejan)/86400000)+onejan.getDay()+1)/7)}`}
function completeWorkout(){state.completed.push({date:new Date().toISOString(),plan:currentPlan(),week:weekId()});state.currentDay++;state.currentExercise=0;state.tab='home';save();render();window.scrollTo({top:0,behavior:'smooth'})}
function startWorkout(){state.currentExercise=0;state.tab='train';save();render();window.scrollTo({top:0,behavior:'smooth'})}
function nextExercise(){const p=plans[currentPlan()];if(state.currentExercise<p.ex.length-1){state.currentExercise++;save();render();window.scrollTo({top:0,behavior:'smooth'})}}
function previousExercise(){if(state.currentExercise>0){state.currentExercise--;save();render();window.scrollTo({top:0,behavior:'smooth'})}}
function icon(){return `<svg viewBox="0 0 100 100" fill="none"><circle cx="50" cy="50" r="43" stroke="white" stroke-width="6" opacity=".35"/><path d="M28 58c10-21 34-21 44 0M35 35h30M50 35v38" stroke="white" stroke-width="7" stroke-linecap="round"/></svg>`}
function shell(content){return `<main class="app">${content}</main><nav class="tabs"><div class="tabs-inner">${['home:Heute','train:Training','progress:Fortschritt','settings:Einstellungen'].map(t=>{let [id,l]=t.split(':');return `<button class="tab ${state.tab===id?'active':''}" onclick="state.tab='${id}';save();render()">${l}</button>`}).join('')}</div></nav>`}
function setup(){return `<main class="app"><section class="hero"><div class="eyebrow">MuskelCoach</div><h1 class="title">Dein Bodyweight-Plan für Muskelaufbau.</h1><p class="sub">Keine Cardio-Challenges. Kein HIIT. Nur saubere Kraftübungen mit Körpergewicht und optionalem Rudergerät.</p></section><section class="card"><h2>Wie oft pro Woche?</h2><div class="grid">${[2,3,4,5].map(d=>`<button class="choice ${state.days===d?'active':''}" onclick="state.days=${d};save();render()">${d}× pro Woche</button>`).join('')}</div></section><section class="card"><h2>Trainingsniveau</h2><div class="switch">${['Einsteiger','Mittel','Fortgeschritten'].map(l=>`<button class="choice ${state.level===l?'active':''}" onclick="state.level='${l}';save();render()">${l}</button>`).join('')}</div></section><section class="card"><h2>Equipment</h2><p class="notice">Voreingestellt: Körpergewicht und optional dein Rudergerät. Weitere Geräte werden nicht benötigt.</p></section><button class="btn" onclick="state.setup=true;save();render()">App starten</button></main>`}
function home(){let p=plans[currentPlan()],done=doneThisWeek(),pct=Math.min(100,Math.round(done/state.days*100));return shell(`<section class="hero"><div class="eyebrow">Heute</div><h1 class="title">${p.name}</h1><p class="sub">${p.focus} · ca. ${state.duration} Minuten · ${state.level}</p></section><section class="card"><div class="row"><div><div class="muted">Wochenfortschritt</div><div class="big">${done} von ${state.days}</div></div><span class="pill">Muskelaufbau</span></div><br><div class="progress"><div class="bar" style="width:${pct}%"></div></div></section><section class="card"><h2>Nächstes Training</h2><p class="muted">${p.ex.length} Übungen · längere Pausen · kontrollierte Wiederholungen</p><button class="btn" onclick="startWorkout()">Training starten</button></section><section class="card"><h2>Prinzip</h2><p class="notice">Die App nutzt bewusst keine Cardio-Übungen. Ziel sind saubere Sätze, passende Pausen und Progression über Wiederholungen oder schwierigere Varianten.</p></section>`)}
function train(){let p=plans[currentPlan()];let total=p.ex.length;let idx=Math.max(0,Math.min(state.currentExercise||0,total-1));state.currentExercise=idx;let id=p.ex[idx];let last=idx===total-1;let pct=Math.round(((idx+1)/total)*100);return shell(`<section class="hero"><div class="eyebrow">Training ${currentPlan()} · Übung ${idx+1} von ${total}</div><h1 class="title">${p.name}</h1><p class="sub">${p.focus}</p></section><section class="card step-card"><div class="row"><b>Übung ${idx+1} von ${total}</b><span class="pill">${pct}%</span></div><br><div class="progress"><div class="bar" style="width:${pct}%"></div></div></section>${exCard(id,idx+1,total)}<section class="card"><div class="timer" id="timer">02:00</div><div class="grid"><button class="btn secondary" onclick="startTimer(120)">Pause 2:00</button><button class="btn secondary" onclick="startTimer(180)">Pause 3:00</button></div></section><div class="training-nav">${idx>0?`<button class="btn secondary" onclick="previousExercise()">Zurück</button>`:''}${last?`<button class="btn" onclick="completeWorkout()">Training abschließen</button>`:`<button class="btn" onclick="nextExercise()">Übung beendet – weiter</button>`}</div>`)}
function exCard(id,number,total){let e=exercises[id],src=GIF_BASE+exerciseGifs[id];return `<article class="card exercise"><div class="visual"><img class="exercise-gif" src="${src}" alt="Animation: ${e.n}" loading="lazy" decoding="async" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><div class="gif-fallback" hidden>${icon()}<span>Animation konnte nicht geladen werden</span></div></div><div class="exbody">${number?`<div class="exercise-number">Übung ${number}${total?` von ${total}`:''}</div>`:''}<h3 class="exname">${e.n}</h3><div class="tagrow"><span class="tag">${e.m}</span><span class="tag">Hypertrophie</span></div><p class="sets">${e.s}</p><p class="notice"><b>Kurz-Tipp:</b> ${e.tip}</p><details class="exercise-details" open><summary>Übungserklärung</summary><div class="detail-content"><h4>Ausführung</h4><p>${e.how}</p><h4>Häufige Fehler</h4><p>${e.errors}</p><h4>Atmung</h4><p>${e.breath}</p><div class="variant-grid"><div><h4>Leichter</h4><p>${e.easy}</p></div><div><h4>Schwieriger</h4><p>${e.hard}</p></div></div></div></details></div></article>`}
function progress(){let total=state.completed.length,streak=Math.min(total,7);return shell(`<section class="hero"><div class="eyebrow">Fortschritt</div><h1 class="title">Deine Kraft-Routine</h1></section><div class="grid"><section class="card"><div class="muted">Trainings gesamt</div><div class="big">${total}</div></section><section class="card"><div class="muted">Serie</div><div class="big">${streak}</div></section></div><section class="card"><h2>Letzte Einheiten</h2><div class="list">${state.completed.slice(-8).reverse().map(x=>`<div class="item"><b>Training ${x.plan}</b><br><span class="muted">${new Date(x.date).toLocaleString('de-DE')}</span></div>`).join('')||'<p class="muted">Noch kein Training abgeschlossen.</p>'}</div></section>`)}
function settings(){return shell(`<section class="hero"><div class="eyebrow">Einstellungen</div><h1 class="title">Dein Plan</h1></section><section class="card"><h2>Trainingshäufigkeit</h2><div class="grid">${[2,3,4,5].map(d=>`<button class="choice ${state.days===d?'active':''}" onclick="state.days=${d};save();render()">${d}×</button>`).join('')}</div></section><section class="card"><h2>Equipment</h2><div class="item">✅ Körpergewicht</div><div class="item">✅ Rudergerät für Rücken-Kraftzüge</div></section><section class="card"><h2>Übungsanimationen</h2><p class="notice">Quelle: Exercises Dataset von hasaneyldrm (nur für private, nicht-kommerzielle Nutzung). Die Animationen werden direkt aus der App geladen und funktionieren auch offline.</p></section><section class="card"><h2>Daten</h2><button class="btn secondary" onclick="exportData()">Backup exportieren</button><br><br><button class="btn secondary" onclick="if(confirm('Alle Daten löschen?')){localStorage.removeItem(STORAGE);state={...defaultState};render()}">Zurücksetzen</button></section>`)}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='muskelcoach-backup.json';a.click()}
let int=null;function startTimer(sec){clearInterval(int);let left=sec;const el=()=>document.getElementById('timer');function tick(){let m=String(Math.floor(left/60)).padStart(2,'0'),s=String(left%60).padStart(2,'0');if(el())el().textContent=`${m}:${s}`;if(left--<=0){clearInterval(int); if(navigator.vibrate)navigator.vibrate(300)}}tick();int=setInterval(tick,1000)}
function render(){document.getElementById('app').innerHTML= state.setup ? ({home,train,progress,settings}[state.tab]||home)() : setup()}
render();
