const STORAGE='muskelcoach-v1';
const defaults={tab:'home',setup:false,days:3,level:'Einsteiger',duration:35,completed:[],currentDay:0,currentExercise:0};
let state=load(); function load(){try{return {...defaults,...JSON.parse(localStorage.getItem(STORAGE)||'{}')}}catch{return {...defaults}}} function save(){localStorage.setItem(STORAGE,JSON.stringify(state))}
const G='images/';
const plans={A:{name:'Push & Beine',focus:'Brust • Schulter • Beine',ex:['pushup','squat','pike','split','plank']},B:{name:'Rücken & Core',focus:'Rücken • hintere Schulter • Bauch',ex:['rower','ytw','superman','angel','hollow']},C:{name:'Ganzkörper Kraft',focus:'Beine • Brust • Core',ex:['diamond','lunge','close','glute','side']}};
const X={
pushup:{n:'Liegestütze',m:'Brust, Trizeps, Schulter, Core',gif:'pushup.webp',sets:'3–4 Sätze',reps:'6–15 Wdh.',pause:'60–90 Sek.',how:'Hände etwas breiter als schulterbreit aufsetzen. Körper von Kopf bis Fuß gerade halten. Brust kontrolliert bis kurz über den Boden absenken und kräftig hochdrücken.',err:'Rücken durchhängen lassen, Ellbogen stark abspreizen oder den Kopf nach vorn schieben.',breath:'Beim Absenken einatmen, beim Hochdrücken ausatmen.',tip:'Bauch und Gesäß fest anspannen. Qualität geht vor Geschwindigkeit.',easy:'Knie-Liegestütze',hard:'Enge Liegestütze'},
squat:{n:'Kniebeugen',m:'Beine, Gesäß, Core',gif:'squat.webp',sets:'4 Sätze',reps:'8–20 Wdh.',pause:'60–90 Sek.',how:'Füße schulterbreit stellen. Hüfte nach hinten und unten führen, Rücken stabil halten und über den ganzen Fuß wieder aufstehen.',err:'Knie nach innen kippen lassen, Fersen anheben oder den Rücken rund machen.',breath:'Beim Absenken einatmen, beim Aufstehen ausatmen.',tip:'Knie folgen den Fußspitzen. Nur so tief gehen, wie die Haltung sauber bleibt.',easy:'Halbe Kniebeugen',hard:'Sprungkniebeugen'},
pike:{n:'Pike Push-ups',m:'Schultern, Trizeps',gif:'pike.webp',sets:'3 Sätze',reps:'6–12 Wdh.',pause:'90 Sek.',how:'Aus dem Liegestütz die Hüfte hochschieben, sodass ein umgedrehtes V entsteht. Kopf kontrolliert zwischen den Händen absenken und wieder hochdrücken.',err:'Hüfte absinken lassen oder den Kopf zu weit vor den Händen absetzen.',breath:'Beim Absenken einatmen, beim Hochdrücken ausatmen.',tip:'Das Gewicht bewusst auf die Hände verlagern.',easy:'Kleine Bewegungsamplitude',hard:'Langsame Abwärtsphase'},
split:{n:'Reverse Lunges',m:'Beine, Gesäß',gif:'split.webp',sets:'3 Sätze',reps:'6–12 je Seite',pause:'60–90 Sek.',how:'Aufrecht stehen und einen großen Schritt nach hinten machen. Hinteres Knie Richtung Boden senken und über die vordere Ferse zurückdrücken.',err:'Zu kurzer Schritt, einknickendes Vorderknie oder nach vorn fallender Oberkörper.',breath:'Beim Absenken einatmen, beim Hochdrücken ausatmen.',tip:'Vorderes Knie stabil über dem Fuß halten.',easy:'Kleinere Tiefe',hard:'Pause in der unteren Position'},
plank:{n:'Unterarmstütz',m:'Core, Schulter, Rücken',gif:'plank.webp',sets:'3 Sätze',reps:'25–60 Sek.',pause:'60 Sek.',how:'Ellbogen unter den Schultern aufsetzen und den Körper von Kopf bis Ferse in einer geraden Linie halten.',err:'Hüfte durchhängen lassen oder zu weit anheben.',breath:'Ruhig und gleichmäßig weiteratmen.',tip:'Bauch und Gesäß dauerhaft anspannen.',easy:'Knie am Boden',hard:'Ein Bein anheben'},
rower:{n:'Rudergerät – Kraftzüge',m:'Rücken, Bizeps, Beine',gif:'rower.webp',sets:'5 Sätze',reps:'8–15 Züge',pause:'90–120 Sek.',how:'Mit geradem Rücken starten, über die Beine Druck aufbauen und den Griff kraftvoll zum unteren Brustkorb ziehen. Rückweg kontrolliert: Arme, Oberkörper, Beine.',err:'Rundrücken, nur aus den Armen ziehen oder hektisch zurückrollen.',breath:'Beim Zug ausatmen, auf dem Rückweg einatmen.',tip:'Dies ist die einzige Übung mit Gerät, da dein Rudergerät bewusst im Plan bleibt.',easy:'Widerstand reduzieren',hard:'Rückweg langsamer ausführen'},
ytw:{n:'Y-T-W Raises in Bauchlage',m:'Oberer Rücken, hintere Schulter',gif:'ytw.webp',sets:'3 Sätze',reps:'6–12 Durchgänge',pause:'60 Sek.',how:'In Bauchlage die Arme nacheinander als Y, T und W anheben. Jede Position kurz halten und die Schulterblätter aktiv zusammenziehen.',err:'Schultern zu den Ohren ziehen oder Schwung holen.',breath:'Beim Anheben ausatmen, beim Absenken einatmen.',tip:'Kleine, kontrollierte Bewegung genügt.',easy:'Nur T-Position',hard:'Länger halten'},
superman:{n:'Superman Hold',m:'Rückenstrecker, Gesäß',gif:'superman.webp',sets:'3 Sätze',reps:'20–45 Sek.',pause:'60 Sek.',how:'In Bauchlage Arme, Brust und Beine leicht anheben. Nacken neutral halten und die Position kontrolliert halten.',err:'Zu stark ins Hohlkreuz ziehen oder ruckartig anheben.',breath:'Ruhig weiteratmen.',tip:'Nur so hoch anheben, wie es angenehm bleibt.',easy:'Nur Arme oder Beine',hard:'Kleine Impulse'},
angel:{n:'Reverse Snow Angels',m:'Oberer Rücken, Schulter',gif:'angel.webp',sets:'3 Sätze',reps:'8–15 Wdh.',pause:'60 Sek.',how:'In Bauchlage die Arme knapp über dem Boden in einem großen Bogen von den Hüften nach vorn und zurückführen.',err:'Arme ablegen, Schwung nutzen oder Schultern hochziehen.',breath:'Beim Vorführen einatmen, beim Zurückführen ausatmen.',tip:'Schulterblätter nach hinten unten ziehen.',easy:'Kleinerer Bewegungsbogen',hard:'Sehr langsam bewegen'},
hollow:{n:'Hollow Hold',m:'Bauch, Core',gif:'hollow.webp',sets:'3 Sätze',reps:'15–45 Sek.',pause:'60 Sek.',how:'Unteren Rücken fest in den Boden drücken. Schulterblätter und Beine leicht anheben und die Spannung halten.',err:'Unterer Rücken löst sich oder Beine werden zu tief gehalten.',breath:'Kurz und kontrolliert weiteratmen.',tip:'Die Rückenlage hat Vorrang vor der Beinhöhe.',easy:'Knie anwinkeln',hard:'Arme über Kopf'},
diamond:{n:'Diamond Push-ups',m:'Trizeps, Brust',gif:'diamond.webp',sets:'3 Sätze',reps:'6–12 Wdh.',pause:'90 Sek.',how:'Hände eng unter der Brust platzieren. Körper gerade halten, Ellbogen nah führen und kontrolliert absenken.',err:'Ellbogen weit nach außen drehen oder Hüfte absinken lassen.',breath:'Beim Absenken einatmen, beim Hochdrücken ausatmen.',tip:'Hände dürfen etwas weiter auseinander stehen, wenn es angenehmer ist.',easy:'Auf den Knien',hard:'Pause unten'},
lunge:{n:'Ausfallschritte',m:'Beine, Gesäß',gif:'lunge.webp',sets:'3 Sätze',reps:'8–14 je Seite',pause:'60–90 Sek.',how:'Einen großen Schritt machen, beide Knie kontrolliert beugen und über die vordere Ferse zurückdrücken.',err:'Zu schmal stehen oder Vorderknie nach innen kippen lassen.',breath:'Beim Absenken einatmen, beim Hochdrücken ausatmen.',tip:'Oberkörper aufrecht halten.',easy:'Reverse Lunge',hard:'Langsame Wiederholungen'},
close:{n:'Enge Liegestütze',m:'Trizeps, Brust',gif:'close.webp',sets:'3 Sätze',reps:'6–12 Wdh.',pause:'90 Sek.',how:'Hände schulterbreit oder etwas enger aufsetzen. Ellbogen nah am Körper führen und den ganzen Körper gespannt bewegen.',err:'Ellbogen abspreizen oder Schultern hochziehen.',breath:'Beim Absenken einatmen, beim Hochdrücken ausatmen.',tip:'Die Hände nicht zu eng setzen.',easy:'Auf den Knien',hard:'Langsame Abwärtsphase'},
glute:{n:'Einbeinige Glute Bridge',m:'Gesäß, Beinrückseite',gif:'glute.webp',sets:'3 Sätze',reps:'8–15 je Seite',pause:'60 Sek.',how:'Auf den Rücken legen, ein Bein aufstellen und das Becken über die Ferse anheben. Oben das Gesäß fest anspannen.',err:'Becken verdrehen oder aus dem unteren Rücken drücken.',breath:'Beim Anheben ausatmen, beim Absenken einatmen.',tip:'Becken gerade halten.',easy:'Beidbeinig',hard:'Oben länger halten'},
side:{n:'Seitstütz',m:'Seitlicher Core, Schulter',gif:'side.webp',sets:'3 Sätze',reps:'20–45 Sek. je Seite',pause:'60 Sek.',how:'Seitlich auf einen Unterarm stützen und die Hüfte anheben, bis der Körper eine gerade Linie bildet.',err:'Hüfte absinken lassen oder Schulter zum Ohr ziehen.',breath:'Ruhig weiteratmen.',tip:'Schulter aktiv vom Ohr wegdrücken.',easy:'Unteres Knie absetzen',hard:'Oberes Bein anheben'}};
function keys(){return ['A','B','C','A','B'].slice(0,state.days)} function pk(){return keys()[state.currentDay%keys().length]} function week(){let d=new Date(),j=new Date(d.getFullYear(),0,1);return d.getFullYear()+'-'+Math.ceil((((d-j)/864e5)+j.getDay()+1)/7)} function done(){return state.completed.filter(x=>x.week===week()).length}
function shell(c){return `<main class="app">${c}</main><nav class="tabs"><div class="tabs-inner">${[['home','⌂','Heute'],['train','◫','Training'],['progress','▥','Fortschritt'],['settings','⚙','Einstellungen']].map(([i,ic,l])=>`<button class="tab ${state.tab===i?'active':''}" onclick="go('${i}')"><span>${ic}</span>${l}</button>`).join('')}</div></nav>`}
function go(t){state.tab=t;save();render();scrollTo(0,0)}
function setup(){return `<main class="app"><section class="hero"><div class="eyebrow">MuskelCoach</div><h1>Dein Krafttraining für zuhause.</h1><p>Nur Körpergewicht – plus dein vorhandenes Rudergerät.</p></section><section class="card"><h2>Trainingstage pro Woche</h2><div class="choicegrid">${[2,3,4,5].map(n=>`<button class="choice ${state.days===n?'active':''}" onclick="state.days=${n};save();render()">${n}×</button>`).join('')}</div></section><button class="primary" onclick="state.setup=true;save();render()">App starten</button></main>`}
function home(){let p=plans[pk()],d=done(),pc=Math.min(100,Math.round(d/state.days*100));return shell(`<header class="top"><b>MuskelCoach</b></header><section class="hero"><div class="eyebrow">Heute ist Trainingstag 💪</div><h1>${p.name}</h1><p>${p.focus} · ${p.ex.length} Übungen · ca. ${state.duration} Min.</p></section><section class="card"><button class="primary" onclick="start()">Training starten</button></section><section class="card"><h2>Wochenfortschritt</h2><div class="big">${d} / ${state.days}</div><div class="progress"><i style="width:${pc}%"></i></div></section><section class="card"><h2>Hinweis</h2><p>Alle Übungen sind ohne Geräte. Nur das Rudergerät bleibt als bewusst ausgewählte Rückenübung enthalten.</p></section>`)}
function start(){state.currentExercise=0;state.tab='train';save();render();scrollTo(0,0)} function prev(){if(state.currentExercise>0){state.currentExercise--;save();render();scrollTo(0,0)}} function next(){let p=plans[pk()];if(state.currentExercise<p.ex.length-1){state.currentExercise++;save();render();scrollTo(0,0)}} function finish(){state.completed.push({date:new Date().toISOString(),plan:pk(),week:week()});state.currentDay++;state.currentExercise=0;state.tab='home';save();render();scrollTo(0,0)}
function train(){let p=plans[pk()],i=Math.min(state.currentExercise,p.ex.length-1),e=X[p.ex[i]],last=i===p.ex.length-1,pc=Math.round((i+1)/p.ex.length*100);return shell(`<header class="trainhead"><button aria-label="Zurück" onclick="go('home')">‹</button><b>Training</b><button class="end" onclick="go('home')">Beenden</button></header><section class="trainintro"><div><span>Übung ${i+1} von ${p.ex.length}</span><h1>${e.n}</h1></div><div class="muscles">${e.m}</div></section><div class="progress trainprogress"><i style="width:${pc}%"></i></div><section class="visual-card"><div class="difficulty">Schwierigkeit: <b>${i<2?'Leicht':'Mittel'}</b></div><div class="media"><img src="${G+e.gif}?v=13" alt="${e.n}" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><div class="fallback" hidden>Animation nicht verfügbar</div></div></section><section class="stats-card"><div class="stats"><div><b>${e.sets}</b><small>Empfehlung</small></div><div><b>${e.reps}</b><small>Wiederholungen</small></div><div><b>${e.pause}</b><small>Pause</small></div></div></section><section class="detail-list"><article class="detail"><div class="detail-icon green">▶</div><div><h3>Ausführung</h3><p>${e.how}</p></div></article><article class="detail"><div class="detail-icon yellow">⚠</div><div><h3>Häufige Fehler</h3><p>${e.err}</p></div></article><article class="detail"><div class="detail-icon red">♨</div><div><h3>Atmung</h3><p>${e.breath}</p></div></article><article class="detail"><div class="detail-icon green">💡</div><div><h3>Tipp</h3><p>${e.tip}</p></div></article></section><div class="variants"><section><h3>↓ Leichtere Variante</h3><p>${e.easy}</p></section><section><h3>↑ Schwierigere Variante</h3><p>${e.hard}</p></section></div><div class="actions">${i?'<button class="secondary" onclick="prev()">← Zurück</button>':'<span></span>'}<button class="primary" onclick="${last?'finish()':'next()'}">${last?'✓ Training abschließen':'Übung beendet – weiter →'}</button></div>`)}
function progress(){return shell(`<header class="top"><b>Fortschritt</b></header><section class="hero"><h1>Deine Trainings</h1></section><div class="twocol"><section class="card"><small>Gesamt</small><div class="big">${state.completed.length}</div></section><section class="card"><small>Diese Woche</small><div class="big">${done()}</div></section></div><section class="card"><h2>Letzte Einheiten</h2>${state.completed.slice(-8).reverse().map(x=>`<p><b>Training ${x.plan}</b><br><small>${new Date(x.date).toLocaleString('de-DE')}</small></p>`).join('')||'<p>Noch kein Training abgeschlossen.</p>'}</section>`)}
function settings(){return shell(`<header class="top"><b>Einstellungen</b></header><section class="card"><h2>Trainingstage</h2><div class="choicegrid">${[2,3,4,5].map(n=>`<button class="choice ${state.days===n?'active':''}" onclick="state.days=${n};save();render()">${n}×</button>`).join('')}</div></section><section class="card"><h2>Equipment</h2><p>✓ Körpergewicht</p><p>✓ Rudergerät ausschließlich für „Rudergerät – Kraftzüge“</p></section><section class="card"><button class="secondary full" onclick="localStorage.removeItem(STORAGE);state={...defaults};render()">App zurücksetzen</button></section>`)}
function render(){document.getElementById('app').innerHTML=state.setup?({home,train,progress,settings}[state.tab]||home)():setup()} render();
